INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Arica y Parinacota');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Tarapacá');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Antofagasta');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Atacama');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Coquimbo');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Valparaíso');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región Metropolitana de Santiago');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región del Libertador General Bernardo OHiggins');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región del Maule');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Ñuble');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región del Biobío');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de La Araucanía');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Los Ríos');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Los Lagos');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Aysén del General Carlos Ibáñez del Campo');
INSERT INTO REGION (RGN_NOMBRE) VALUES ('Región de Magallanes y de la Antártica Chilena');

--
INSERT INTO COMUNA (COM_NOMBRE, RGN_ID) VALUES ('TEMUCO', 12);
INSERT INTO COMUNA (COM_NOMBRE, RGN_ID) VALUES ('PADRE LAS CASAS', 12);
--
INSERT INTO ESTABLECIMIENTO (EST_NOMBRE, EST_DIRECCION, COM_ID) VALUES ('HOSPITAL DOCTOR HERNÁN HENRÍQUEZ ARAVENA','Manuel Montt 115', 1);
INSERT INTO ESTABLECIMIENTO (EST_NOMBRE, EST_DIRECCION, COM_ID) VALUES ('COMPLEJO ASISTENCIAL PADRE LAS CASAS','Long Sur', 2);